name: CI .NET 7

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ./dotnet-CI.sln

      - name: Build
        run: dotnet build ./dotnet-CI.sln --no-restore

      - name: Run Tests
        run: dotnet test ./dotnet-CI.sln --no-build --verbosity normal

      - name: Build Docker image
        if: success()
        run: docker build -t dotnet-ci-app .
